# SITE CONFIGURATION
baseurl: "/"
url: "https://lmohrmann.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Lars Mohrmann                                    # site's title
description: "Personal web page of Lars Mohrmann"       # used by search engines
avatar: assets/img/portrait.jpg                         # Empty for no avatar in navbar
favicon: assets/img/icon_milky_way.jpg                             # Icon displayed in the tab

# Header and footer text
header_text: Lars Mohrmann  # Change Blog header text
header_subtitle: Researcher in <br> high-energy astrophysics
header_feature_image: assets/img/HESS_GalacticPlane_AA_CoverImage_2018.png
footer_text: © Copyright Lars Mohrmann 2022.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: false
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: dark                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  research_experiments:
    output: true
    permalink: /:collection/:name
  research_projects:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: lmohrmann/Type-on-Strap                     # If using as a remote_theme in github
